name: Build and Publish Docker image to GHCR

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag variable
        id: tag
        run: |
          echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: Build Docker image with version and latest tags
        run: |
          docker build \
            -t ghcr.io/TranziaNet/tranzia:${{ steps.tag.outputs.tag_name }} \
            -t ghcr.io/TranziaNet/tranzia:latest \
            .

      - name: Push Docker image with tags
        run: |
          docker push ghcr.io/TranziaNet/tranzia:${{ steps.tag.outputs.tag_name }}
          docker push ghcr.io/TranziaNet/tranzia:latest
